//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visita
    {
        public decimal id_visita { get; set; }
        public string fecha_visita { get; set; }
        public string hora_visita { get; set; }
        public decimal id_guia { get; set; }
        public decimal numero_identificacion { get; set; }
    
        public virtual Guia Guia { get; set; }
        public virtual Visitante Visitante { get; set; }
    }
}
